- MiSTer_SAM_on.sh
Reverts mrchrisster/MiSTer_SAM#43
> Revert "Add files via upload"

- .MiSTer_SAM/MiSTer_SAM_MCP
- .MiSTer_SAM/MiSTer_SAM_init
- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
Avoid killing inotifywait processes we didn't start
> Add optional tty2oled support

- MiSTer_SAM_on.sh
This makes logo->text transitions look better on the TTY2OLED display.
> Update with Venice's latest improvements to TTY2OLED support

- MiSTer_SAM.ini
Adding "ttyuseack" to INI and set to "Yes".
Please decide if you want this setting set to **Yes** or **No**.
Cheers
> Adding ttyuseack to INI and set to "Yes"

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
Also fix mgl creation
Update MiSTer_SAM.ini
> Add Handling for extended Paths

- MiSTer_SAM_on.sh
This is for testing purposes only, after you have your results, saved and reported to the team, disable this for normal operation
> Add speedtest for usedefaultpaths and create_romlists

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
As far as I can tell, everything works exactly as before...
> Refactored most of the code changed speedtest to a commandline switch

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
Gamelist generation has been updated
Fix a typo in speedtest that kept one test from running, at all
No longer delete temporary gamelists, so, as long as you don't reboot, it really will play every game before repeating, if you have that option enabled.
Turned more code into reusable functions, some of which will be used later to allow regenerating the gamelists, when needed.
> Changes to many  things

- MiSTer_SAM_on.sh
This will later be expanded to be a time selected by the user "day week month" etc.
> Regenerate gamelists once a week on start

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
Update all variables for correct types
This removes the need to cast a variable to lowercase, as they are declared lowercase, with a few exceptions, including input from the commandline, and, when needing to do a lowercase compare of a normally agnostic case variable (such as checking file extensions)
Add variables for duration between regenerating game lists and add settings to ini
> More refactoring and game list creation changes

- MiSTer_SAM_on.sh
Unescaped directories with spaces are no good...
fixed logic error in menu status detection
> Fix a couple of small issues

- MiSTer_SAM_on.sh
For now, these extensions are hardcoded in the script, and there are a few extensions that have been excluded until they can be properly tested.
> Multiple extensions Now Supported for many cores

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
> No core repeat

- MiSTer_SAM_on.sh
No longer kills SAM autostart
Exposes global variables as actually global
processes startup initializations needed for speedtest and create-gamelists without processing more of the script than necessary, some commands need further testing, such as enable disable and update
help option needs to be updated for this new system, as well.
> Process commandline options and fix playcurrentgame logic

- MiSTer_SAM_on.sh
Add a timeout to the read of the "ack" for not blocking SAM if something goes wrong.
While loop not needed.
> Add tty2oled read timeout

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
Mostly changes to handling command line switches and commands
New way to handle muting and unmuting the Global volume, and start implementing muting only the core, allowing scripts like BGM to play music and sounds over the Attract mode.
Some general cleanups
Allow the stop and --stop commands to exit, gracefully, running cleanup, so we don't leave bind mounts behind, etc.
> Many big changes

- MiSTer_SAM_on.sh
Choices are now
Yes (Global volume mute)
No (Don't mute anything)
Core (Only mute the core volume)
This allows the BGM script, or, other music players, to work while Attract mode runs on mute.
Fixed a small parsing error in the NEOGEO Title Lists.
> Update muting system

- .MiSTer_SAM/MiSTer_SAM_MCP
- .MiSTer_SAM/MiSTer_SAM_init
- .MiSTer_SAM/MiSTer_SAM_tty2oled
- MiSTer_SAM_control.sh
- MiSTer_SAM_on.sh
Fix using MiSTer_SAM_on.sh start to quickstart SAM
Some code and visual cleanup
> Several small fixes

- MiSTer_SAM_on.sh
Changes to skipmessage, which still don't seem to fix the issue with FDS and TGFX16-CD
add TTY2OLED script to update
> Small updates

- .MiSTer_SAM/MiSTer_SAM_joy.py
Change DEBUG to True and it'll print out the detected device id and the id of a button/axis. Will make it easy to add your own controllers.
> Add debug flag to joy script

- MiSTer_SAM_on.sh
A new variable named configpath is set. By default, it points to /media/fat/config. However, if the cfgcore_subfolder entry is defined in MiSTer.ini, it is used to extend the path. Likewise, if cfgarcade_subfolder is set, its configuration folder will be used in the arcade cores
More information about the aitorgomez fork can be found here:
https://github.com/spark2k06/Main_MiSTer
> Compatibility with the main MiSTer project from the 'aitorgomez' fork.
