- MiSTer_SAM_on.sh
I would like to be able to specify some behavior on a per game basis. An ideal implementation would handle the following use cases:
- Specify a unique attract mode time value.
- Ability to script a single button press after some amount of time. This would be useful for some GBA games that have `Health and Safety` warning screens so that they can be skipped automatically. 
- A general configuration option to filter out games without per-game configuration files.
- Some kind of probability control.
This MR implements a basic version of this. It uses a complimentary `$(romname).sam` file next to game rom to specify custom properties. Currently only handles overriding the countdown value per game.
A couple of examples:
```bash
counter=172
```
```bash
counter=90
simulate_a_press=3 
```
This is …
> Optional per-game configuration files.

- README.md
I noticed the readme referenced an "orientation" setting that doesn't seem to exist. I've updated it to be a bit more accurate
> Update readme to no longer refer to an "orientation" option

- MiSTer_SAM_on.sh
If you have a customized MRA list, it gets clobbered each time MiSTer_SAM_on.sh runs, deleting any changes you previously made.
> Prevent customized MRA list from being overwritten if it exists

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
This patch addresses issue #90 by introducing optional whitelist files for each console core. If the file exists and is not empty, only games from the list will be used.
The change is accomplished by adding tests to `find` such that ROM files that are not in the whitelist, and zip files that don't contain at least one ROM in the whitelist, are excluded from `find`'s output. The whitelist is also used when selecting which random ROM to extract from the zip file.
A simpler approach would've been to check the whitelist right before the exclude list, but during testing I found this would result in a large number of skips and calls to `next_core` if the whitelist is small relative to the number of ROMs. Filtering the files during the `find` command ensures the script doesn't waste time …
> Console whitelists and configurable MiSTer_SAM repository

- MiSTer_SAM_on.sh
This addresses an issue similar to #81. Since save files, save states, screenshots, etc rely on the ROM name, renaming the extracted ROM breaks this functionality. With this change, unzipped ROMs are extracted to /tmp/MiSTer_SAM/ with their original file names.  Since the files won't get overwritten any more, it also cleans up the /tmp/MiSTer_SAM directory immediately prior to unzipping another ROM.
> Keep the file name of unzipped ROMs.

- .MiSTer_SAM/MiSTer_SAM_MCP
- .MiSTer_SAM/MiSTer_SAM_init
The code responsible for finding the PID of inotifywait isn't working. My guess is MiSTer changed its `ps` implementation at some point and the current version of `ps` has a different output format from when this code was written. The current `ps` version tries to align its output using multiple spaces, which makes `cut` impractical.
The new code specifies the output columns for `ps` and uses `read`'s built-in word splitting to parse the PID. Hopefully this'll be more resilient to formatting changes.
> Fix cleanup code for inotifywait.

- .MiSTer_SAM/MiSTer_SAM_init
- MiSTer_SAM_on.sh
- Implements tmux session (widely used/understood and conveniently included with MiSTer-FPGA's Linux distro) to handle monitoring, enabling scrollback, copy/paste, prevent user killing process by accident, etc etc with no changes to structure, and no relying on tty voodoo
- Kills MiSTer_SAM related processes thoroughly, but carefully
- Removes redundant kill attempts after proper kill executes
- Still works w/ fresh install and setup automation as-shipped (*SHOULD, hardcoded repo-specific changes reverted before PR obviously)
> Monitoring via tmux plus start/stop fixes

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
Moin,
the SAM INI contains only tty2oled yes/no and the paths to the tty2oled ini files which will be sourced at tty_init.
Means you get tty device and picture paths from the tty2oled configuration.
New ist tty_exit which starts the tty2oled daemon if tty2oled was set to yes.
I use now "${CORE_LAUNCH[${1,,}]}" and "${CORE_LAUNCH[${nextcore},,}]}" (for Arcade) to identify the corename 
which is needed to find the core picture. 
This should be the right one now as a fds game is now loding the nes picture.
Cheers
> tty2oled Support Updates

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
This will allow SAM to automatically find the Rom paths, even if some are on /media/fat/games/ and others are on /media/usb(0-5)/games/ as well as a few other paths searched by MiSTer and the cores.
> Allow Use Default Rom Paths

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
If the user wants to only use roms in a subfolder of the main rom directory, it must be added in the pathextra fields
Somehow the genesis/s32x mix up got missed in the ini file, in a previous commit
echo left out of the stop commandline option
> Some quick error fixes

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
I found a few use cases that didn't work with the previous setup, including extensions that were uppercase, in zips and, it also wasn't searching subdirectories for zip files and would choke on zips with spaces in their names
Added sounds to filenames to ignore (I have some .pce files that just play sounds from games, no visuals...)
I also added a line that backs up the previous mgl file before creating the new one, for debugging purposes.
One benefit of this is you don't need to keep roms for systems in completely separate directories, such as GB and GBC the script will only select the proper roms for each system, from all the zips it finds.
I also added code to prevent it searching for zips for systems that don't use zips, for some reason with PSX, it would think some chds were zips, …
> Fix romlist creation to use all roms and zips

- MiSTer_SAM_on.sh
When you stop SAM, MiSTer should return to the main menu, it was never reaching that command, due to sam_stop killing the process, it also wasn't unmuting the system.
> Fix the Stop command

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
This allows testing to see if one method has a speed advantage over the other
Some kind of caching happens after the script runs the first time, so, it is recommended that, after changing the type, in the ini, you reboot to make sure you get the real numbers for each method.
> Add Static and Dynamic code branches

- MiSTer_SAM_on.sh
Added function to allow processing multiple file extensions (not supported, yet) For now, it just continues to work as it did before.
> Fix game list regeneration when using startmonitor instead of start

- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
Atari2600 was, long ago, merged with the ATARI7800 core, and, the rom files need to be in the ATARI7800 folder for mgl to work, until something is changed in the cores/mgl code, you can use the pathsextra fields to separate them into separate directories, under ATARI7800 if you wish, which will keep the gamelist creator from scanning both sets of files for each core.
usedefaultpaths only takes a couple of seconds, so, is not "slow" and will be enabled by default. You can keep it set to No or, set it to No if you'd like, and, it will continue to work, somewhat, but, will become unsupported.
Everdrive mappings have been made obsolete, and have been removed, this affects nobody, as we don't use them for anything.
There is still work to be done, for example, many Atari 5200 games need a left …
> Add Atari 2600 5200 7800 and Lynx

- MiSTer_SAM_on.sh
If you press a key on a keyboard, move the mouse, or press a button on a controller, if the sound is muted, and you have playcurrentgame set to yes, it will unmute, and reload the game (this is required to enable sound) if the sound is not muted, it will just exit and leave the game playing, otherwise, it will exit to the main mister menu.
> Finally fix play_or_exit

- MiSTer_SAM_on.sh
Choices are now
Yes (Global volume mute)
No (Don't mute anything)
Core (Only mute the core volume)
This allows the BGM script, or, other music players, to work while Attract mode runs on mute.
Fixed a small parsing error in the NEOGEO Title Lists.
> Update muting system

- .MiSTer_SAM/MiSTer_SAM_joy.py
This new version of the joy detect script includes joysticks and dpads in detection. It also has optional support for detecting individual buttons. It should be a drop in replacement for the current script.
As discussed, I don't believe it will ever be possible to use mister's existing mapping files, since it uses evdev codes and these devices are always busy when you want to use them. I'm proposing an alternative solution to manually maintain a map of common controllers' buttons to their js device event codes instead. I've included a working example of it for the PS4 controller. This method of detection won't ever be perfect, but I think it will work well enough for most users.
> Update joypad detection with dpad and specific buttons

- .MiSTer_SAM/MiSTer_SAM_tty2oled
Moin/Hi,
as I wrote in one of my last mails I added a few more **tty_waitfor** in the tty part of SAM.
This will give more stabilty for 8266 usage.
I run a test with a 8266 with the serial chip CH340G, the same ESP as Antonio sells.
With the little delay in MiSTer_SAM_on.sh I get everything running and I get the MENU Logo each time back to the display with both ESPs.
```
function tty_exit() {
if [ "${ttyenable}" == "yes" ]; then
echo -n " Stopping tty2oled... "
tmux kill-session -t OLED &>/dev/null
sleep 1 #TEST 
rm "${tty_sleepfile}" &>/dev/null
echo "Done."
fi
```
As a note, I never recommend 8266.
Antonio or one of his corporate never asked which device they should take.
> More 8266 stabilty

- .MiSTer_SAM/MiSTer_SAM.default.ini
- .MiSTer_SAM/MiSTer_SAM_init
- .MiSTer_SAM/MiSTer_SAM_menu
- .MiSTer_SAM/tools-extras/SAM-HDMIcapture.sh
- MiSTer_SAM.ini
- MiSTer_SAM_on.sh
I don't have a blacklist file, but I've confirmed that this works with the handful of coco2 cartridges I tried with an attract screen.
> Add support for coco2 cartridges.

- MiSTer_SAM_on.sh
Define the `setname` element of the MGL for gg and gbc cores matching their standard MGL `setname`s so things like the DV1 infoframe can better describe the core in use.
> Define setname for gg and gbc cores
